// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Varzea.Data;

#nullable disable

namespace Varzea.Data.Migrations
{
    [DbContext(typeof(VarzeaDbContext))]
    [Migration("20260806173941_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Varzea.Data.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CareerSlotId")
                        .HasColumnType("uuid");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("CareerSlotId");

                    b.HasIndex("PlayerId", "PeriodType", "PeriodKey")
                        .IsUnique();

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Varzea.Data.Entities.CareerSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<double>("AwardsScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int[]>("DraftPicks")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<double>("PeakScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<double>("ProductionScore")
                        .HasColumnType("double precision");

                    b.Property<string>("RulesetVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Seed")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<double>("TitlesScore")
                        .HasColumnType("double precision");

                    b.Property<bool[]>("TransferChoices")
                        .IsRequired()
                        .HasColumnType("boolean[]");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "SlotIndex")
                        .IsUnique()
                        .HasFilter("NOT \"Archived\"");

                    b.ToTable("CareerSlots");
                });

            modelBuilder.Entity("Varzea.Data.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Varzea.Data.Entities.Achievement", b =>
                {
                    b.HasOne("Varzea.Data.Entities.CareerSlot", "CareerSlot")
                        .WithMany()
                        .HasForeignKey("CareerSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Varzea.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerSlot");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Varzea.Data.Entities.CareerSlot", b =>
                {
                    b.HasOne("Varzea.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
